In [1]:
import numpy as np
from kick import kick

In [2]:
hostname = 'localhost'
username = 'root'
password = 'root'
port = 32771
# hostname="3.208.94.164"
# username="ubuntu"
# key_filename="test.pem"

In [3]:
a = np.ones((5,1))
a

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [4]:
b = np.ones((1,5))
b

array([[1., 1., 1., 1., 1.]])

In [5]:
@kick
def matmul(a, b):
    return a.dot(b)

initialize


In [6]:
matmul(a, b)

>>  numpy found
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

