In [11]:
import numpy as np
from Kick import kick_web

In [12]:
a = np.random.rand(4, 4)
b = np.random.rand(4, 4)

In [13]:
a.dot(b)

array([[0.86983788, 0.7063232 , 0.38849109, 0.92141015],
       [1.5308224 , 1.69662519, 0.82284114, 2.06502167],
       [0.91667442, 1.13211161, 0.38082245, 1.19444932],
       [0.96585905, 1.17997047, 0.51970361, 1.41235405]])

In [14]:
@kick_web
def matmul(a, b):
    return a.dot(b)

>> initialize


In [16]:
c = matmul(a, b)

[[1.2416106  0.55910762 0.69703909 0.70765646]
 [2.4075267  1.13992253 1.47486529 1.05101594]
 [2.25183152 1.26711627 1.35230986 1.28470277]
 [1.74106834 0.97434373 1.0974327  0.83844974]]


In [17]:
c

array([[1.2416106 , 0.55910762, 0.69703909, 0.70765646],
       [2.4075267 , 1.13992253, 1.47486529, 1.05101594],
       [2.25183152, 1.26711627, 1.35230986, 1.28470277],
       [1.74106834, 0.97434373, 1.0974327 , 0.83844974]])