In [9]:
import socket
import numpy as np
import jsonpickle

def from_bytes(b):
    """convert bytes back to python object.
    """
    j = b.decode('UTF-8')  # from bytes to json
    o = jsonpickle.decode(j)  # from json to python object
    return o

def up(port, fname):
    """send fname to server and retrieve corresponding results.
    
    # https://stackoverflow.com/questions/9382045/send-a-file-through-sockets-in-python
    """
    # create socket and connect
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect(('3.236.152.182', port)) 

    # send source to server
    with open(fname, "rb") as f:
        l = f.read(1024)
    s.send(l) 
        
    # receive results from server and unpack bytes to numpy
    res = s.recv(1024)
    o = from_bytes(res)  # https://markhneedham.com/blog/2018/04/07/python-serialize-deserialize-numpy-2d-arrays/
    # o = np.frombuffer(res)
    print(o)
    
    # close the connection 
    if res:
        s.close()
        return o
    else:
        raise ValueError

In [11]:
up(port=1111, fname="foobar.py")  # port should match server port

[[1.1607805  1.72548163 0.41491881 1.92575164]
 [1.32565961 1.64162547 0.74098217 2.03195966]
 [0.56812238 1.13913728 0.43107429 1.23335938]
 [0.75077297 1.61910368 0.62200392 1.74323728]]


array([[1.1607805 , 1.72548163, 0.41491881, 1.92575164],
       [1.32565961, 1.64162547, 0.74098217, 2.03195966],
       [0.56812238, 1.13913728, 0.43107429, 1.23335938],
       [0.75077297, 1.61910368, 0.62200392, 1.74323728]])