In [3]:
import socket
import numpy as np
import jsonpickle

def from_bytes(b):
    """convert bytes back to python object.
    """
    j = b.decode('UTF-8')  # from bytes to json
    o = jsonpickle.decode(j)  # from json to python object
    return o

def up(port, fname):
    """send fname to server and retrieve corresponding results.
    
    # https://stackoverflow.com/questions/9382045/send-a-file-through-sockets-in-python
    """
    # create socket and connect
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect(('3.236.152.182', port)) 

    # send source to server
    with open(fname, "rb") as f:
        l = f.read(1024)
    s.send(l) 
        
    # receive results from server and unpack bytes to numpy
    res = s.recv(1024)
    o = from_bytes(res)  # https://markhneedham.com/blog/2018/04/07/python-serialize-deserialize-numpy-2d-arrays/
    # o = np.frombuffer(res)
    print(o)
    
    # close the connection 
    if res:
        s.close()
        return o
    else:
        raise ValueError

In [4]:
a = up(port=1111, fname="foobar.py")  # port should match server port

[[1.95220124 2.25474372 2.31782812 1.27065894]
 [1.43875174 1.53152338 1.54475967 0.83070755]
 [1.2310306  1.3923315  1.40934274 0.79931545]
 [1.52196836 1.67479069 1.68661692 0.99452482]]


In [6]:
a

array([[1.95220124, 2.25474372, 2.31782812, 1.27065894],
       [1.43875174, 1.53152338, 1.54475967, 0.83070755],
       [1.2310306 , 1.3923315 , 1.40934274, 0.79931545],
       [1.52196836, 1.67479069, 1.68661692, 0.99452482]])