In [9]:
import socket
import numpy as np
import jsonpickle

def from_bytes(b):
    """convert bytes back to python object.
    """
    j = b.decode()  # from bytes to json
    o = jsonpickle.decode(j)  # from json to python object
    return o

def up(port, fname):
    """send fname to server and retrieve corresponding results.
    
    # https://stackoverflow.com/questions/9382045/send-a-file-through-sockets-in-python
    """
    # create socket and connect
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect(('localhost', port)) 

    # send source to server
    with open(fname, "rb") as f:
        l = f.read(1024)
    s.send(l) 
        
    # receive results from server and unpack bytes to numpy
    res = s.recv(1024)
    o = from_bytes(res)  # https://markhneedham.com/blog/2018/04/07/python-serialize-deserialize-numpy-2d-arrays/
    print(o)
    
    # close the connection 
    if res:
        s.close()
        return o
    else:
        raise ValueError

In [11]:
up(4002, "foobar.py")

[[ 93.58376672  19.96360773  78.18941     60.60797077]
 [122.86759221  90.39791146 117.84743214  68.01817012]
 [146.97214129  89.02200835 102.95620591  95.38213342]
 [111.65000672  53.9488396  101.27108878  62.70355913]]


array([[ 93.58376672,  19.96360773,  78.18941   ,  60.60797077],
       [122.86759221,  90.39791146, 117.84743214,  68.01817012],
       [146.97214129,  89.02200835, 102.95620591,  95.38213342],
       [111.65000672,  53.9488396 , 101.27108878,  62.70355913]])