In [1]:
import socket
import numpy as np
import jsonpickle

def from_bytes(b):
    """convert bytes back to python object.
    """
    j = b.decode('UTF-8')  # from bytes to json
    o = jsonpickle.decode(j)  # from json to python object
    return o

def up(port, fname):
    """send fname to server and retrieve corresponding results.
    
    # https://stackoverflow.com/questions/9382045/send-a-file-through-sockets-in-python
    """
    # create socket and connect
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect(('3.236.152.182', port)) 

    # send source to server
    with open(fname, "rb") as f:
        l = f.read(1024)
    s.send(l) 
        
    # receive results from server and unpack bytes to numpy
    res = s.recv(1024)
    o = from_bytes(res)  # https://markhneedham.com/blog/2018/04/07/python-serialize-deserialize-numpy-2d-arrays/
    # o = np.frombuffer(res)
    print(o)
    
    # close the connection 
    if res:
        s.close()
        return o
    else:
        raise ValueError

In [2]:
a = up(port=1111, fname="foobar.py")  # port should match server port

[[1.1265366  0.89255023 0.650524   0.62098519]
 [0.66799725 0.63130461 0.40494075 0.42892255]
 [1.09759406 0.77707    0.81158675 0.76770551]
 [1.62245357 1.40025039 0.95896779 1.15035   ]]


In [3]:
a

array([[1.1265366 , 0.89255023, 0.650524  , 0.62098519],
       [0.66799725, 0.63130461, 0.40494075, 0.42892255],
       [1.09759406, 0.77707   , 0.81158675, 0.76770551],
       [1.62245357, 1.40025039, 0.95896779, 1.15035   ]])

In [7]:
a * 3

array([[3.37960979, 2.6776507 , 1.951572  , 1.86295557],
       [2.00399176, 1.89391383, 1.21482225, 1.28676765],
       [3.29278218, 2.33121001, 2.43476024, 2.30311652],
       [4.8673607 , 4.20075118, 2.87690338, 3.45105001]])

In [4]:
a * 2

array([[2.25307319, 1.78510047, 1.301048  , 1.24197038],
       [1.3359945 , 1.26260922, 0.8098815 , 0.8578451 ],
       [2.19518812, 1.55414   , 1.62317349, 1.53541101],
       [3.24490713, 2.80050078, 1.91793559, 2.30070001]])

In [8]:
globals()["In"]

['',
 'import socket\nimport numpy as np\nimport jsonpickle\n\ndef from_bytes(b):\n    """convert bytes back to python object.\n    """\n    j = b.decode(\'UTF-8\')  # from bytes to json\n    o = jsonpickle.decode(j)  # from json to python object\n    return o\n\ndef up(port, fname):\n    """send fname to server and retrieve corresponding results.\n    \n    # https://stackoverflow.com/questions/9382045/send-a-file-through-sockets-in-python\n    """\n    # create socket and connect\n    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\n    s.connect((\'3.236.152.182\', port)) \n\n    # send source to server\n    with open(fname, "rb") as f:\n        l = f.read(1024)\n    s.send(l) \n        \n    # receive results from server and unpack bytes to numpy\n    res = s.recv(1024)\n    o = from_bytes(res)  # https://markhneedham.com/blog/2018/04/07/python-serialize-deserialize-numpy-2d-arrays/\n    # o = np.frombuffer(res)\n    print(o)\n    \n    # close the connection \n    if res:\n 

In [10]:
locals()['a']

array([[1.1265366 , 0.89255023, 0.650524  , 0.62098519],
       [0.66799725, 0.63130461, 0.40494075, 0.42892255],
       [1.09759406, 0.77707   , 0.81158675, 0.76770551],
       [1.62245357, 1.40025039, 0.95896779, 1.15035   ]])

In [11]:
globals()['a']

array([[1.1265366 , 0.89255023, 0.650524  , 0.62098519],
       [0.66799725, 0.63130461, 0.40494075, 0.42892255],
       [1.09759406, 0.77707   , 0.81158675, 0.76770551],
       [1.62245357, 1.40025039, 0.95896779, 1.15035   ]])